package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/nqxcode/chat_microservice/internal/service.LogService -o ./mocks\log_service_minimock.go -n LogServiceMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/nqxcode/chat_microservice/internal/model"
)

// LogServiceMock implements service.LogService
type LogServiceMock struct {
	t minimock.Tester

	funcCreate          func(ctx context.Context, message *model.Log) (err error)
	inspectFuncCreate   func(ctx context.Context, message *model.Log)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mLogServiceMockCreate
}

// NewLogServiceMock returns a mock for service.LogService
func NewLogServiceMock(t minimock.Tester) *LogServiceMock {
	m := &LogServiceMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mLogServiceMockCreate{mock: m}
	m.CreateMock.callArgs = []*LogServiceMockCreateParams{}

	return m
}

type mLogServiceMockCreate struct {
	mock               *LogServiceMock
	defaultExpectation *LogServiceMockCreateExpectation
	expectations       []*LogServiceMockCreateExpectation

	callArgs []*LogServiceMockCreateParams
	mutex    sync.RWMutex
}

// LogServiceMockCreateExpectation specifies expectation struct of the LogService.Create
type LogServiceMockCreateExpectation struct {
	mock    *LogServiceMock
	params  *LogServiceMockCreateParams
	results *LogServiceMockCreateResults
	Counter uint64
}

// LogServiceMockCreateParams contains parameters of the LogService.Create
type LogServiceMockCreateParams struct {
	ctx     context.Context
	message *model.Log
}

// LogServiceMockCreateResults contains results of the LogService.Create
type LogServiceMockCreateResults struct {
	err error
}

// Expect sets up expected params for LogService.Create
func (mmCreate *mLogServiceMockCreate) Expect(ctx context.Context, message *model.Log) *mLogServiceMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("LogServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &LogServiceMockCreateExpectation{}
	}

	mmCreate.defaultExpectation.params = &LogServiceMockCreateParams{ctx, message}
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the LogService.Create
func (mmCreate *mLogServiceMockCreate) Inspect(f func(ctx context.Context, message *model.Log)) *mLogServiceMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for LogServiceMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by LogService.Create
func (mmCreate *mLogServiceMockCreate) Return(err error) *LogServiceMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("LogServiceMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &LogServiceMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &LogServiceMockCreateResults{err}
	return mmCreate.mock
}

// Set uses given function f to mock the LogService.Create method
func (mmCreate *mLogServiceMockCreate) Set(f func(ctx context.Context, message *model.Log) (err error)) *LogServiceMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the LogService.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the LogService.Create method")
	}

	mmCreate.mock.funcCreate = f
	return mmCreate.mock
}

// When sets expectation for the LogService.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mLogServiceMockCreate) When(ctx context.Context, message *model.Log) *LogServiceMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("LogServiceMock.Create mock is already set by Set")
	}

	expectation := &LogServiceMockCreateExpectation{
		mock:   mmCreate.mock,
		params: &LogServiceMockCreateParams{ctx, message},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up LogService.Create return parameters for the expectation previously defined by the When method
func (e *LogServiceMockCreateExpectation) Then(err error) *LogServiceMock {
	e.results = &LogServiceMockCreateResults{err}
	return e.mock
}

// Create implements service.LogService
func (mmCreate *LogServiceMock) Create(ctx context.Context, message *model.Log) (err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, message)
	}

	mm_params := &LogServiceMockCreateParams{ctx, message}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_got := LogServiceMockCreateParams{ctx, message}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("LogServiceMock.Create got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the LogServiceMock.Create")
		}
		return (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, message)
	}
	mmCreate.t.Fatalf("Unexpected call to LogServiceMock.Create. %v %v", ctx, message)
	return
}

// CreateAfterCounter returns a count of finished LogServiceMock.Create invocations
func (mmCreate *LogServiceMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of LogServiceMock.Create invocations
func (mmCreate *LogServiceMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to LogServiceMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mLogServiceMockCreate) Calls() []*LogServiceMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*LogServiceMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *LogServiceMock) MinimockCreateDone() bool {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateInspect logs each unmet expectation
func (m *LogServiceMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LogServiceMock.Create with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to LogServiceMock.Create")
		} else {
			m.t.Errorf("Expected call to LogServiceMock.Create with params: %#v", *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		m.t.Error("Expected call to LogServiceMock.Create")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LogServiceMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockCreateInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LogServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LogServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone()
}
